---
title: "They Should Not Be Rebooting *Murder, She Wrote*"
#subtitle: ""
format:
    qarticle2-pdf:
      keep-tex: FALSE
biblio-style: apsr
anonymous: FALSE
thanks: "Replication files are available on the author's Github account (http://github.com/svmiller/svm-r-markdown-templates). **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: steven.v.miller@gmail.com."
title-subtitle: FALSE
author:
- name: Steven V. Miller
  affiliations:
    - ref: su
- name: A Second Author Who Did Less Work
  affiliations: The Ohio State University
- name: A Graduate Student
  affiliations: University of Alabama
affiliations:
  - id: su
    name: Stockholm University
    department: Institutionen för ekonomisk historia och internationella relationer
    address: Universitetsvägen 10A, 114 18 Stockholm, Sweden
abstract: "
They should not be [rebooting *Murder, She Wrote*](https://www.theguardian.com/film/2026/mar/25/jamie-lee-curtis-murder-she-wrote-reboot). That show was wonderful; truly one of mankind's greatest artistic achievements. However, some things are just a moment in time that you can't get back and trying to get them back is just lazily reheating intellectual property for dinner. This is *Murder, She Wrote*, not baked ziti. The idea that 1) a book writer can 2) live in apparently the murder (per capita) capital of the world, 3) moonlight as a detective, 4) actively interfere with police investigations, and 5) somehow coerce confessions *every single time* from people who do not know how to keep their damn mouth shut is just something that does not age well today. Viewers expect forensic evidence that was almost never acknowledged on that show. Plus, Jamie Lee Curtis is probably okay but she's no Angela Lansbury. There is no actor befitting William Windom's role of Dr. Seth Hazlitt. Just, please, don't. Do something else."
keywords: "pandoc, quarto, Angela Lansbury, Hollywood has run out of ideas, memberberries, William Windom is a woefully underappreciated character actor"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=2.5cm
mainfont: cochineal
sansfont: Libertinus Sans
removetitleabstract: FALSE
fontsize: 12pt
# doublespacing: TRUE
endnotes: FALSE
endfloat: TRUE
pandocparas: TRUE
acmsans: FALSE
paper-info:
  - "*DOI*: 10.4320/ICU8.1.2"
  - "*JEL Codes*: A1, B2, C3, D4, Battleship Sunk!"
---

```{r setup, include=FALSE}
is_docx <- knitr::pandoc_to("docx")
is_latex <- knitr::pandoc_to("latex")

knitr::opts_chunk$set(fig.path='_figs/',
                      cache.path = '_cache/',
                      fig.process = function(x) {
                      x2 = sub('-\\d+([.][a-z]+)$', '\\1', x)
                      if (file.rename(x, x2)) x2 else x
                      })

#library(kableExtra)
library(tinytable)
library(stevedata)
library(tidyverse)
# Uncomment below if you want code captions
# oldSource <- knitr::knit_hooks$get("source")
# knitr::knit_hooks$set(source = function(x, options) {
#   x <- oldSource(x, options)
#   x <- ifelse(!is.null(options$code.cap), paste0(x, "\\captionof{chunk}{", options$code.cap,"}"), x)
#   ifelse(!is.null(options$ref), paste0(x, "\\label{", options$ref,"}"), x)
# })
# Add `chunkcaption: TRUE` to YAML as well.

```


# Introduction

{{< lipsum 1 >}}

```{r}
1 + 1
```

Here is a footnote you can make an endnote if you'd like.[^fn]

[^fn]: You'll just have to trust me on this.


# Literature Review

{{< lipsum 2-5 >}}


# Theory

{{< lipsum 6-8 >}}

# Research Design

{{< lipsum 9-12 >}}

# Analysis

```{r}
#| fig-cap: A Plot of mtcars
#| label: fig-mtcars
plot(mtcars)
```

{{< lipsum 13-17 >}}

```{r, echo= F}
#| tbl-cap: Mitchell's (1968) Data Set
#| label: tbl-mitchell68
#| 
# Mitchell68 %>% select(-id) %>%
#   kbl(., col.names = c("Province", "Govt. Control",
#                        "Owner-Operated Land", "CV Land-Holdings",
#                        "Vietnamese Land", "French Land", "Mobility",
#                        "Pop. Density"),
#       align = c("lccccccc"),
#       linesep = "",
#       booktabs = TRUE, longtable = TRUE) %>%
#   row_spec(0, bold = TRUE) %>%
#   kable_styling(font_size = 7)

tt(Mitchell68)

```


# Conclusion

{{< lipsum 18-19 >}}